name: Flutter CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [master]

  push:
    branches: [master]

jobs:
  flutter_ci:
    name: Run Flutter CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter 3.29.3
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Run code generation
        run: |
          flutter gen-l10n
          flutter pub run build_runner build --delete-conflicting-outputs

      - name: Check formatting
        run: dart format -o none --set-exit-if-changed lib/

      - name: Run tests
        run: flutter test

      - name: Analyze
        run: dart analyze --fatal-infos lib/
